language: r
dist: focal
latex: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

branches:
  except:
    - master

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: test
  local_dir: public
  target_branch: master
