language: r
sudo: false
cache: packages

before_install:
  - wget https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.deb
  - sudo dpkg -i hugo_0.21_Linux-64bit.deb

script:
  - make build
  - ls public
