dist: xenial
language: cpp
sudo: required

branches:
  except:
    - master

before_install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.86.1/hugo_extended_0.86.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - export HUGO_CACHEDIR=/.cache
  - sudo mkdir -p $HUGO_CACHEDIR
  - sudo chmod a+wrx $HUGO_CACHEDIR

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  local_dir: public
  target_branch: master
