# Site settings
title: HBS RCS
email: research@hbs.edu
description: > # this means to ignore newlines until "baseurl:"
  Research Computing Services at Harvard Business School.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hbs-rcs.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: hbs-rcs

# Build settings
highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

permalink: pretty

theme: jekyll-theme-modernist