# Site settings
title: HBS RCS
email: research@hbs.edu
description: > # this means to ignore newlines until "baseurl:"
  Research Computing Services at Harvard Business School.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username: hbs-rcs

# Build settings
markdown: kramdown

permalink: pretty
