theme: "hugo-PaperMod"
baseURL: https://hbs-rcs.github.io
languageCode: en-us
title: HBS Research Computing Services Blog
menu:
    main:
        - name: All Posts
          url: archives/
        - name: Posts by Topic
          url: tags
        - name: Search
          url: search/
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    defaultTheme: light
    ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowToc: true
