baseurl = "https://hbs-rcs.github.io/"
relativeurls = true
languageCode = "en-us"
title = "HBS RCS"
theme = "simple-a"
googleAnalytics = ""
disqusShortname = "hbs-rcs"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/hbs-rcs/hbs-rcs.github.io"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml", "stata", "bash"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.svg"
    width = 50
    height = 50
    alt = "Logo"
